// products
GET http://localhost:3000/api/products
###

GET http://localhost:3000/api/products/677b0123fbfd14a29ee53b92
###

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "food",
    "quantity": 8,
    "price": 99
}
###

PUT http://localhost:3000/api/products/677b4441d50b18342a427178
Content-Type: application/json

{
    "name": "laptop",
    "quantity": 9,
    "price": 200
}
###

DELETE http://localhost:3000/api/products/677b0123fbfd14a29ee53b92
###

// users
GET http://localhost:3000/api/users/677d9019d1d814342f209c80
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2Q5MDE5ZDFkODE0MzQyZjIwOWM4MCIsInVzZXJuYW1lIjoiTWFyayIsImlhdCI6MTczNjI4MzQ4MCwiZXhwIjoxNzM2Mjg3MDgwfQ.7usgaK4ifhhzeWrBdrtajRG51MJzVp2zIlxujvld2fc
###

POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "username": "Mark",
    "password": "hey"
}
###

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "Mark",
    "password": "hey"
}
###

PUT http://localhost:3000/api/users/677c8e02473d8af4d192a78b
Content-Type: application/json

{
    "username": "Mark",
    "password": "hey"
}
###

DELETE http://localhost:3000/api/users/677bf689d5ae2920b065bd89
###


POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "Mark",
    "password": "hey"
}
###